# Generated by Django 4.2.7 on 2024-03-30 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "account_type",
                    models.IntegerField(
                        choices=[(1, "Personal"), (2, "Foreign"), (3, "System")],
                        default=1,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("show_on_dashboard", models.BooleanField(default=False)),
                ("iban", models.CharField(blank=True, max_length=34, null=True)),
                ("import_ibans", models.TextField(default="[]")),
                ("import_names", models.TextField(default="[]")),
            ],
            options={
                "ordering": ["-active", "name"],
                "unique_together": {("name", "account_type")},
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.IntegerField(
                        choices=[
                            (1, "Deposit"),
                            (2, "Withdrawal"),
                            (3, "Transfer"),
                            (4, "Reconcile"),
                        ]
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("recurrence", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="main.category",
                    ),
                ),
                (
                    "dst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="main.account",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debits",
                        to="main.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.category"
                    ),
                ),
            ],
            options={
                "ordering": ["category"],
            },
        ),
    ]
